server:
  ssl:
    key-store: "classpath:keystores/server.jks"
    key-store-password: "password"
    key-store-type: "JKS"
    key-password: "password"
    key-alias: "server"
    client-auth: need
    trust-store-type: "JKS"
    trust-store: "classpath:keystores/truststore.jks"
    trust-store-password: "password"
  port: 443